[Unit]
Name = "komorebi-bar"
Description = "Status bar for komorebi"
Requires = ["komorebi"]

[Service]
Kind = "Simple"
Environment = [[
    "KOMOREBI_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]
Restart = "Never"

[Service.ExecStart]
Executable = "komorebi-bar.exe"
Arguments = [
    "--config",
    "$USERPROFILE/.config/komorebi/komorebi.bar.json",
]

[Service.Healthcheck.Process]
DelaySec = 1
