#!/usr/bin/env bash

export STATUS_FILE="$XDG_RUNTIME_DIR/touchpad.status"

# Set device to be toggled
HYPRLAND_DEVICE="$(hyprctl devices | grep touchpad | sed -e 's/\s*//')"
HYPRLAND_VARIABLE="device[$HYPRLAND_DEVICE]:enabled"

if [ -z "$XDG_RUNTIME_DIR" ]; then
	export XDG_RUNTIME_DIR=/run/user/$(id -u)
fi

enable_touchpad() {
	printf "true" >"$STATUS_FILE"
	dunstify --urgency=0 "Enabled Touchpad"
	hyprctl keyword $HYPRLAND_VARIABLE true
}

disable_touchpad() {
	printf "false" >"$STATUS_FILE"
	dunstify --urgency=0 "Disabled Touchpad"
	hyprctl keyword $HYPRLAND_VARIABLE false
}

if ! [ -f "$STATUS_FILE" ]; then
	enable_touchpad
else
	if [ $(cat "$STATUS_FILE") = "true" ]; then
		disable_touchpad
	elif [ $(cat "$STATUS_FILE") = "false" ]; then
		enable_touchpad
	fi
fi
