#!/usr/bin/env bash

case $1 in
ac)
	hyprctl keyword monitor "eDP-1,1920x1080@144,0x0,1"
	~/.config/waybar/scripts/launch
	hyprctl reload
	swww init
	dbus-launch kdeconnect-cli
	syncthing serve --no-browser
	notify-send "Animations Enabled, running @144Hz" -u low
	;;
bat)
	hyprctl keyword monitor "eDP-1,1920x1080@60,0x0,1"
	~/.config/waybar/scripts/launch
	hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:blur 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding "
	swww kill
	pkill syncthing
	pkill kdeconnect
	notify-send "Animations Disabled running @60Hz" -u low
	;;
*)
	notify-send "Invalid option" -u low
	;;
esac
