#!/bin/sh

case $1 in
ac)
	hyprctl keyword monitor "eDP-1,1920x1080@144,0x0,1"
	hyprctl reload
	dunstify "Switched to AC mode" --urgency=0
	swww init
	;;
bat)
	hyprctl keyword monitor "eDP-1,1920x1080@60,0x0,1"
	hyprctl --batch "\
	       keyword animations:enabled 0;\
	       keyword decoration:blur:enabled 0;\
	       keyword general:gaps_in 0;\
	       keyword general:gaps_out 0;\
	       keyword general:border_size 1;\
	       keyword decoration:rounding "
	pkill syncthing
	pkill kdeconnect
	pkill swww
	dunstify "Switched to Battery mode" --urgency=0
	;;
esac
