#!/bin/sh

$HOME/.config/hypr/scripts/switch_monitors.sh

case $1 in
ac)
	swww-daemon
	kdeconnectd
	systemctl --user start syncthing.service
	tailscale up
	hyprctl reload
	notify-send "Switched to AC mode"
	;;
bat)
	hyprctl --batch "\
	       keyword animations:enabled 0;\
	       keyword decoration:blur:enabled 0;\
	       keyword general:gaps_in 0;\
	       keyword general:gaps_out 0;\
	       keyword general:border_size 1;\
	       keyword decoration:rounding "
	pkill syncthing
	tailscale down
	pkill kdeconnect
	pkill swww
	notify-send "Switched to Battery mode" --urgency=0
	;;
esac
