#!/usr/bin/env bash

# Set env vars for sxhkd
if ! [[ -x "$(command -v nixos-version)" ]]; then
	export BROWSER=brave-browser-beta
else
	export BROWSER=brave
fi

feh --bg-fill ~/tmp/wallpaper
xinput set-prop "ELAN1205:00 04F3:30E9 Touchpad" "libinput Tapping Enabled" 1
~/.config/scripts/fix_scrolling
picom &
sxhkd &
kanata &
clipmenud &
nm-applet &
~/.config/polybar/launch.sh
