#!/usr/bin/env bash

"$HOME/.config/scripts/display_setup.sh"

# Set env vars for sxhkd
if ! [[ -x "$(command -v nixos-version)" ]]; then
	export BROWSER=brave-browser-beta
else
	export BROWSER=brave
fi

xinput set-prop "ELAN1205:00 04F3:30E9 Touchpad" "libinput Tapping Enabled" 1
~/.config/scripts/fix_scrolling
sxhkd &
kanata &
clipmenud &
nm-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
kdeconnectd &
greenclip daemon &
mkfifo /tmp/xobpipe && tail -f /tmp/xobpipe | xob -t 2170 & disown
