#!/usr/bin/env bash

rofi_command="rofi -theme $HOME/.config/rofi/config/powermenu.rasi"

# Options
ddir="$HOME/.config/rofi/config"

shutdown="⏻"
reboot=""
lock=""
suspend="󰒲"
logout="󰍃"

# Ask for confirmation
rdialog() {
	rofi -dmenu -i -no-fixed-num-lines -p "Are You Sure? : " \
		-theme "$ddir/confirm.rasi"
}

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 0)"
case $chosen in
$shutdown)
	ans=$(rdialog &)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
		systemctl poweroff
	else
		show_msg
	fi
	;;
$reboot)
	ans=$(rdialog &)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
		systemctl reboot
	else
		show_msg
	fi
	;;
$lock)
	betterlockscreen -l
	;;
$suspend)
	ans=$(rdialog &)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
		mpc -q pause
		amixer set Master mute
		betterlockscreen -l
		systemctl suspend
	else
		show_msg
	fi
	;;
$logout)
	ans=$(rdialog &)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
		i3-msg exit
	else
		show_msg
	fi
	;;
esac
