#!/usr/bin/env bash

rofi_command="rofi -theme $HOME/.config/rofi/config/refresh.rasi"

chosen="$(echo -e "144\n60" | $rofi_command -dmenu -selected-row 0)"
case $chosen in
144)
	xrandr -r 144
	;;
60)
	xrandr -r 60
	;;
esac
