#!/usr/bin/env bash

rm -rf ~/.config/zsh/plugins/
cd ~/.config/zsh/
mkdir -p plugins && cd plugins
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
git clone https://github.com/zsh-users/zsh-autosuggestions
git clone https://github.com/zdharma-continuum/fast-syntax-highlighting
git clone https://github.com/zsh-users/zsh-history-substring-search.git
git clone https://github.com/zsh-users/zsh-completions
git clone https://github.com/hlissner/zsh-autopair.git
git clone https://github.com/jeffreytse/zsh-vi-mode.git

rm -rf ~/.config/tmux/plugins/tpm/
cd ~/.config/tmux/
mkdir -p plugins && cd plugins
git clone https://github.com/tmux-plugins/tpm
