#!/usr/bin/env bash

feh --bg-fill /home/keshav/Pictures/wallpapers/willow_rays.png
xinput set-prop "ELAN1205:00 04F3:30E9 Touchpad" "libinput Tapping Enabled" 1
~/.config/scripts/fix_scrolling
picom -b --experimental-backends --config ~/.config/picom/picom.conf
sxhkd &
clipmenud &
nm-applet &
~/.config/polybar/launch.sh
