#!/bin/bash

cd ~/.config/zsh/
mkdir -p plugins
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
git clone https://github.com/zsh-users/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
git clone https://github.com/zsh-users/zsh-history-substring-search.git
git clone https://github.com/zsh-users/zsh-completions
git clone https://github.com/hlissner/zsh-autopair.git
git clone https://github.com/jeffreytse/zsh-vi-mode.git
