return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = { enable = true },
    autotag = { enable = true },
    indent = { enable = true },
    auto_install = true,
    ensure_installed = {
      "bash",
      "c",
      "comment",
      "cpp",
      "css",
      "diff",
      "dockerfile",
      "git_rebase",
      "gitcommit",
      "gitignore",
      "go",
      "html",
      "java",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "jsonc",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "rust",
      "typescript",
      "tsx",
      "vim",
      "yaml",
    },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "<C-space>",
        node_incremental = "<C-space>",
        scope_incremental = false,
        node_decremental = "<bs>",
      },
    },
  },
}
