#!/usr/bin/env bash

rofi_command="rofi -theme $HOME/.config/rofi/config/profiles.rasi"

chosen="$(echo -e "󱐌\n󱟢" | $rofi_command -dmenu -selected-row 0)"
case "$chosen" in
󱐌)
	. "$HOME"/.config/scripts/battery_status_change "ac"
	;;
󱟢)
	. "$HOME"/.config/scripts/battery_status_change "bat"
	;;
esac
