#!/usr/bin/env bash

# Set env vars for sxhkd
if ! [[ -x "$(command -v nixos-version)" ]]; then
	export BROWSER=brave-browser-beta
else
	export BROWSER=brave
fi

feh --bg-fill /home/keshav/Pictures/wallpapers/bg_9.jpg
xinput set-prop "ELAN1205:00 04F3:30E9 Touchpad" "libinput Tapping Enabled" 1
~/.config/scripts/fix_scrolling
picom -b --config ~/.config/picom/picom.conf
sxhkd &
clipmenud &
nm-applet &
~/.config/polybar/launch.sh
